name: "Build & Scan Image"

# This worflow needs those secrets:
#
# DOCKERPASSWORD = Docker Hub token

on:
  workflow_call:
  workflow_dispatch:

env:
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64"     # Build for which platforms
  DOCKER_USER: "tdeutsch"                                            # Which user to use to login to DockerHub
  UPSTREAM_GITHUB_REPOSITORY: "mxpv/podsync"                         # Upstream repo

#####
# To rebuild someone else's repo, do this:
#
# - New env    REPOSITORY: "githubuser/githubrepo"
# - Add this to the checkout:
#        with:
#          repository: ${{ env.REPOSITORY }}
# - One may also need to disable hadolint, due to the quality of others Dockerfile
#####

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Build
        id: get_version
        run: |
          VERSION=$(curl --silent https://api.github.com/repos/${{env.UPSTREAM_GITHUB_REPOSITORY}}/tags  | jq -r '.[0].name' | sed -e 's/^v//')
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            VERSION="v${VERSION}"
          fi
          IMAGENAME=$(echo ${{ github.repository }} | sed 's/${{ github.repository_owner }}\/docker-//g')
          docker build --build-arg UPSTREAM_VERSION=${VERSION} -t ${IMAGENAME}:scan .
      -
        name: Test the image with Snyk for high-severity vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.prep.outputs.imagename }}:scan
          args: --file=Dockerfile --severity-threshold=high
