name: "Build & Scan"

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
  workflow_dispatch:

env:
  UPSTREAM_GITHUB_REPOSITORY: "mxpv/podsync"                         # Upstream repo

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.2
      -
        name: Get current version
        id: get_version
        run: |
          version=$(curl --silent https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/tags | jq -r '.[-1].ref' | awk -F/ '{print $NF}')
          if [[ $version =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            version="v${version}"
          fi
          echo "::debug::get current version ${version}"
          echo "::set-output name=version::${version}"
      -
        name: Generate Build-Args
        id: build-args
        run: |
          echo ::set-output name=build-arg1::"UPSTREAM_VERSION=${{ steps.get_version.outputs.version }}"
          # echo ::set-output name=build-arg2::"buildarg2"
      -
        name: Prepare
        id: prep
        run: |
          IMAGENAME=$(echo ${{ github.repository }} | sed 's/${{ github.repository_owner }}\/docker-//g')
          echo ::set-output name=imagename::${IMAGENAME}
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.prep.outputs.imagename }}:test
          build-args: |
            ${{ steps.build-args.outputs.build-arg1 }}
            ${{ steps.build-args.outputs.build-arg2 }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache