name: "CI: Linting Dockerfile"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.2
      -
        name: hadolint
        uses: reviewdog/action-hadolint@v1.33.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
