name: "Linting Dockerfile"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.2
      -
        name: Hadolint
        uses: brpaz/hadolint-action@v1.5.0
        with: 
          dockerfile: Dockerfile
