name: "Test"

# This worflow needs those secrets:
#
# DOCKERPASSWORD = Docker Hub token

on:
  schedule:
    - cron: '3 3 * * *'
  workflow_dispatch:
  repository_dispatch:
    types:
      - 'new-version'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64"     # Build for which platforms
  DOCKER_USER: "tdeutsch"                                            # Which user to use to login to DockerHub
  UPSTREAM_GITHUB_REPOSITORY: "mxpv/podsync"                         # Upstream repo

#####
# To rebuild someone else's repo, do this:
#
# - New env    REPOSITORY: "githubuser/githubrepo"
# - Add this to the checkout:
#        with:
#          repository: ${{ env.REPOSITORY }}
# - One may also need to disable hadolint, due to the quality of others Dockerfile
#####

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  ci-build:
    uses: ./.github/workflows/ci-build.yml
  
  scan:
    needs: [ci-build]
    uses: ./.github/workflows/scan.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
